sims/main/routes.py
from flask import render_template, Blueprint
import logging
from sims.users.utils import read_json

main = Blueprint("main", __name__)

options = read_json("sims/vars.json")["options"]

@main.route("/")
@main.route("/home")
def home():
    logging.info("App initialized")
    return render_template('home.html')


@main.route("/main.about")
def about():
    logging.info("Entering about endpoint")
    return render_template('about.html', title="Application Sim-Search")


@main.route("/main_page")
def main_page():
    logging.info("Entering home endpoint")
    return render_template('main.html', posts=options)

sims/users/routes.py
import os
import sims
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from sims import db, bcrypt
from sims.models import User
from sims.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                              RequestResetForm, ResetPasswordForm)
from sims.users.utils import save_picture, send_reset_email
import logging

users = Blueprint("users", __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("Vous êtes déjà identifié, vous pouvez utiliser Sim-Search.", "success")
        return redirect(url_for("main.home"))

    form = RegistrationForm()

    if len([f for f in os.listdir(os.path.dirname(sims.__file__)) if f.endswith(".db")]) == 0:
        db.create_all()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Le compte pour {form.username.data} a bien été crée! \
        Veuillez vous connecter pour pouvoir utiliser Sim-Search', 'success')
        logging.info(f"New account created. login: {form.username.data}.")
        return redirect(url_for("main.home"))


    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Le compte pour {form.username.data} a bien été crée! \
        Veuillez vous connecter pour pouvoir utiliser Sim-Search', 'success')
        logging.info(f"New account created. login: {form.username.data}.")
        return redirect(url_for("main.home"))
    return render_template('register.html', title="S'inscrire", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            logging.info(f"Logged as: {form.email.data}.")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Connexion refusée. Veillez vérifier le nom d'utilisateur et le mot de passe", 'danger')
    return render_template('login.html', title='Connexion', form=form)


@users.route("/logout")
def logout():
    logout_user()
    logging.info(f"User logged out.")
    return redirect(url_for("main.home"))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, current_app)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Vos informations ont bien été mises à jour.", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Mon compte',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        logging.warning(f"{user} asked for password reset. Mail containting token sent.")
        flash(f'Un mail vous a été envoyé à {user} avec les instructions pour réinitialiser votre mot de passe.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Réinitialiser le mot de passe', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Le token utilisé a expiré ou est incorrect.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        logging.warning(f"Password for {user} was reset successfully.")
        flash("Votre mot de passe a bien été modifié, vous pouvez vous connecter dès à présent.", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

sims/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>Fonctionnement de cette application </h1>
{% endblock content %}

sims/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Mon compte</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <div class="media-body">
        <a href="{{ url_for('main.main_page') }}">
            <img class="center" src= "static/img/main.jpg">
        </a>
    </div>
{% endblock content %}

sims/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Sim-Search</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href='{{ url_for("main.home") }}'>Sim-Search</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.main_page') }}">Recherches</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">Projet</a>
              {% if messages %}
                <a class="nav-item nav-link" href="{{ url_for('users.about') }}">Projet</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Mon compte</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Deconnexion</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Connexion</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">S'inscrire</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %} <br><br><br>
        </div>
        <div class="col-md-4"><small>
          <div class="content-section">
            <h5>Informations diverses</h5>
            <p class='text-muted'>Informations sur les modèles utilisés
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Deep Metric Learning</li>
                <li class="list-group-item list-group-item-light">Architecture</li>
                <li class="list-group-item list-group-item-light">Performances</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </small></div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

sims/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Connexion</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Mot de pass oublié ?</a>
                </small>
            </div>

        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Vous n'avez pas de compte ? <a class="ml-2" href="{{ url_for('users.register') }}">Inscrivez-vous</a>
        </small>
    </div>
{% endblock content %}

sims/templates/main.html
{% extends "layout.html" %}

{% block content %}
    {% for field in posts %}
        <article class="media content-section">
          <div class="media-body" >
            <div class="article-metadata">
              <a class="mr-2" >{{ field.tete }}</a>
              <small class="text-muted">{{ field.sous_titre }}</small>
            </div>
<!--            <h2><a class="article-title-with-link" href="inference.simil">{{ field.title }}</a></h2>-->
            <h2><a class="article-title-with-link" href="{{ url_for(field.url_name) }}">{{ field.title }}</a></h2>
            <p class="article-content">{{ field.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

sims/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Inscrivez-vous</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Déjà inscrit ?<a class="ml-2" href="{{ url_for('users.login') }}">Connexion</a>
        </small>
    </div>
{% endblock content %}

sims/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Réinitialiser le mot de passe</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Réinitialiser le mot de passe</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/simil.html
{% extends "layout.html" %}
{% block content %}
    <h1>Images Similaires</h1><br>
        <article class="media content-section">
          <div class="media-body">
            <p class="article-content">{{ task.content }}</p>
          </div>
        </article>

        <h4 class="article-content">Télécharger une image</h4>

        <article class="media content-section">
            <div class="media-body">
                <p>
                    <form  method=post enctype=multipart/form-data><br>
                    <input type=file name=file> <br><br>
                    <input type=submit value=Télécharger>
                    <input type=number value=10 name=nb_responses> <br><br></form>
                </p>
          </div>
        </article>
{% endblock content %}

sims/templates/simil_2.html
{% extends "layout.html" %}
{% block content %}
    <h1>Images Similaires</h1><br>
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-content">Votre image</h4><br>
                <img src= "{{ full_path }}" alt="User image" width="300">
            </div>
        </article>
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-content">Images similaires</h4><br>
                {% for im in resp %}
                <img src= "{{ im }}" alt="" width="300">
                <p></p>
                {% endfor %}
            </div>
        </article>

{% endblock content %}

sims/templates/tri.html
{% extends "layout.html" %}
{% block content %}
    <h1>Tri d'images</h1><br>
        <article class="media content-section">
          <div class="media-body">
            <p class="article-content">{{ task.content }}</p>
          </div>
        </article>

        <h4 class="article-content">Votre dossier :</h4>

        <article class="media content-section">
            <div class="media-body">
                <p>
                    <br>
                    <form  method=post enctype=multipart/form-data>
                    <input type="file" id="filepicker" name="fileList" webkitdirectory multiple /><br><br>
                    <input type=submit value=Séléction>
                    <ul id="listing"></ul>
                </p>
          </div>
        </article>
{% endblock content %}

sims/templates/tri_pred.html
{% extends "layout.html" %}
{% block content %}
    <h1>Tri d'images</h1><br>
        <article class="media content-section">
            <div class="media-body">
                <h4 class="article-content">Vos images</h4><br>
                <img src= "{{ file_list }}" alt="User image" width="30">
            </div>
        </article>
        <article class="media content-section">
            <div class="media-body">

                <h4 class="article-content">Le tri :</h4><br>
<!--                {% for im in file_list %}-->
<!--                <img src= "{{ im }}" alt="" width="300">-->
                <p>{{ file_list }}</p>
<!--                {% endfor %}-->
            </div>
        </article>

{% endblock content %}